//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//*****************************************************************************
//
// Notes on the ETW event code generated by MC:
//
// - Structures and arrays of structures are treated as an opaque binary blob.
//   The caller is responsible for packing the data for the structure into a
//   single region of memory, with no padding between values. The macro will
//   have an extra parameter for the length of the blob.
// - Arrays of nul-terminated strings must be packed by the caller into a
//   single binary blob containing the correct number of strings, with a nul
//   after each string. The size of the blob is specified in characters, and
//   includes the final nul.
// - If a SID is provided, its length will be determined by calling
//   GetLengthSid.
// - Arrays of SID are treated as a single binary blob. The caller is
//   responsible for packing the SID values into a single region of memory with
//   no padding.
// - The length attribute on the data element in the manifest is significant
//   for values with intype win:UnicodeString, win:AnsiString, or win:Binary.
//   The length attribute must be specified for win:Binary, and is optional for
//   win:UnicodeString and win:AnsiString (if no length is given, the strings
//   are assumed to be nul-terminated). For win:UnicodeString, the length is
//   measured in characters, not bytes.
// - For an array of win:UnicodeString, win:AnsiString, or win:Binary, the
//   length attribute applies to every value in the array, so every value in
//   the array must have the same length. The values in the array are provided
//   to the macro via a single pointer -- the caller is responsible for packing
//   all of the values into a single region of memory with no padding between
//   values.
// - Values of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary can be generated and collected on Vista or later.
//   However, they may not decode properly without the Windows 10 2018 Fall
//   Update.
// - Arrays of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary must be packed by the caller into a single region of
//   memory. The format for each item is a UINT16 byte-count followed by that
//   many bytes of data. When providing the array to the generated macro, you
//   must provide the total size of the packed array data, including the UINT16
//   sizes for each item. In the case of win:CountedUnicodeString, the data
//   size is specified in WCHAR (16-bit) units. In the case of
//   win:CountedAnsiString and win:CountedBinary, the data size is specified in
//   bytes.
//
//*****************************************************************************

#include <wmistr.h>
#include <evntrace.h>
#include <evntprov.h>

#if !defined(ETW_INLINE)
#define ETW_INLINE DECLSPEC_NOINLINE __inline
#endif

#if defined(__cplusplus)
extern "C" {
#endif

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_USE_KERNEL_MODE_APIS macro:
// Controls whether the generated code uses kernel-mode or user-mode APIs.
// - Set to 0 to use Windows user-mode APIs such as EventRegister.
// - Set to 1 to use Windows kernel-mode APIs such as EtwRegister.
// Default is based on whether the _ETW_KM_ macro is defined (i.e. by wdm.h).
// Note that the APIs can also be overridden directly, e.g. by setting the
// MCGEN_EVENTWRITETRANSFER or MCGEN_EVENTREGISTER macros.
//
#ifndef MCGEN_USE_KERNEL_MODE_APIS
  #ifdef _ETW_KM_
    #define MCGEN_USE_KERNEL_MODE_APIS 1
  #else
    #define MCGEN_USE_KERNEL_MODE_APIS 0
  #endif
#endif // MCGEN_USE_KERNEL_MODE_APIS

//
// MCGEN_HAVE_EVENTSETINFORMATION macro:
// Controls how McGenEventSetInformation uses the EventSetInformation API.
// - Set to 0 to disable the use of EventSetInformation
//   (McGenEventSetInformation will always return an error).
// - Set to 1 to directly invoke MCGEN_EVENTSETINFORMATION.
// - Set to 2 to to locate EventSetInformation at runtime via GetProcAddress
//   (user-mode) or MmGetSystemRoutineAddress (kernel-mode).
// Default is determined as follows:
// - If MCGEN_EVENTSETINFORMATION has been customized, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else if the target OS version has EventSetInformation, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else set to 2 (i.e. try to dynamically locate EventSetInformation).
// Note that an McGenEventSetInformation function will only be generated if one
// or more provider in a manifest has provider traits.
//
#ifndef MCGEN_HAVE_EVENTSETINFORMATION
  #ifdef MCGEN_EVENTSETINFORMATION             // if MCGEN_EVENTSETINFORMATION has been customized,
    #define MCGEN_HAVE_EVENTSETINFORMATION   1 //   directly invoke MCGEN_EVENTSETINFORMATION(...).
  #elif MCGEN_USE_KERNEL_MODE_APIS             // else if using kernel-mode APIs,
    #if NTDDI_VERSION >= 0x06040000            //   if target OS is Windows 10 or later,
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EtwSetInformation" via MmGetSystemRoutineAddress.
    #endif                                     // else (using user-mode APIs)
  #else                                        //   if target OS and SDK is Windows 8 or later,
    #if WINVER >= 0x0602 && defined(EVENT_FILTER_TYPE_SCHEMATIZED)
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EventSetInformation" via GetModuleHandleExW/GetProcAddress.
    #endif
  #endif
#endif // MCGEN_HAVE_EVENTSETINFORMATION

//
// MCGEN_EVENTWRITETRANSFER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTWRITETRANSFER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTWRITETRANSFER   EtwWriteTransfer
  #else
    #define MCGEN_EVENTWRITETRANSFER   EventWriteTransfer
  #endif
#endif // MCGEN_EVENTWRITETRANSFER

//
// MCGEN_EVENTREGISTER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTREGISTER        EtwRegister
  #else
    #define MCGEN_EVENTREGISTER        EventRegister
  #endif
#endif // MCGEN_EVENTREGISTER

//
// MCGEN_EVENTSETINFORMATION macro:
// Override to use a custom API.
// (McGenEventSetInformation also affected by MCGEN_HAVE_EVENTSETINFORMATION.)
//
#ifndef MCGEN_EVENTSETINFORMATION
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTSETINFORMATION  EtwSetInformation
  #else
    #define MCGEN_EVENTSETINFORMATION  EventSetInformation
  #endif
#endif // MCGEN_EVENTSETINFORMATION

//
// MCGEN_EVENTUNREGISTER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTUNREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTUNREGISTER      EtwUnregister
  #else
    #define MCGEN_EVENTUNREGISTER      EventUnregister
  #endif
#endif // MCGEN_EVENTUNREGISTER

//
// MCGEN_PENABLECALLBACK macro:
// Override to use a custom function pointer type.
// (Should match the type used by MCGEN_EVENTREGISTER.)
//
#ifndef MCGEN_PENABLECALLBACK
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_PENABLECALLBACK      PETWENABLECALLBACK
  #else
    #define MCGEN_PENABLECALLBACK      PENABLECALLBACK
  #endif
#endif // MCGEN_PENABLECALLBACK

//
// MCGEN_GETLENGTHSID macro:
// Override to use a custom API.
//
#ifndef MCGEN_GETLENGTHSID
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_GETLENGTHSID(p)      RtlLengthSid((PSID)(p))
  #else
    #define MCGEN_GETLENGTHSID(p)      GetLengthSid((PSID)(p))
  #endif
#endif // MCGEN_GETLENGTHSID

//
// MCGEN_EVENT_ENABLED macro:
// Controls how the EventWrite[EventName] macros determine whether an event is
// enabled. The default behavior is for EventWrite[EventName] to use the
// EventEnabled[EventName] macros.
//
#ifndef MCGEN_EVENT_ENABLED
#define MCGEN_EVENT_ENABLED(EventName) EventEnabled##EventName()
#endif

//
// MCGEN_EVENT_BIT_SET macro:
// Implements testing a bit in an array of ULONG, optimized for CPU type.
//
#ifndef MCGEN_EVENT_BIT_SET
#  if defined(_M_IX86) || defined(_M_X64)
#    define MCGEN_EVENT_BIT_SET(EnableBits, BitPosition) ((((const unsigned char*)EnableBits)[BitPosition >> 3] & (1u << (BitPosition & 7))) != 0)
#  else
#    define MCGEN_EVENT_BIT_SET(EnableBits, BitPosition) ((EnableBits[BitPosition >> 5] & (1u << (BitPosition & 31))) != 0)
#  endif
#endif // MCGEN_EVENT_BIT_SET

//
// MCGEN_ENABLE_CHECK macro:
// Determines whether the specified event would be considered as enabled
// based on the state of the specified context. Slightly faster than calling
// McGenEventEnabled directly.
//
#ifndef MCGEN_ENABLE_CHECK
#define MCGEN_ENABLE_CHECK(Context, Descriptor) (Context.IsEnabled && McGenEventEnabled(&Context, &Descriptor))
#endif

#if !defined(MCGEN_TRACE_CONTEXT_DEF)
#define MCGEN_TRACE_CONTEXT_DEF
typedef struct _MCGEN_TRACE_CONTEXT
{
    TRACEHANDLE            RegistrationHandle;
    TRACEHANDLE            Logger;      // Used as pointer to provider traits.
    ULONGLONG              MatchAnyKeyword;
    ULONGLONG              MatchAllKeyword;
    ULONG                  Flags;
    ULONG                  IsEnabled;
    UCHAR                  Level;
    UCHAR                  Reserve;
    USHORT                 EnableBitsCount;
    PULONG                 EnableBitMask;
    const ULONGLONG*       EnableKeyWords;
    const UCHAR*           EnableLevel;
} MCGEN_TRACE_CONTEXT, *PMCGEN_TRACE_CONTEXT;
#endif // MCGEN_TRACE_CONTEXT_DEF

#if !defined(MCGEN_LEVEL_KEYWORD_ENABLED_DEF)
#define MCGEN_LEVEL_KEYWORD_ENABLED_DEF
//
// Determines whether an event with a given Level and Keyword would be
// considered as enabled based on the state of the specified context.
// Note that you may want to use MCGEN_ENABLE_CHECK instead of calling this
// function directly.
//
FORCEINLINE
BOOLEAN
McGenLevelKeywordEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ UCHAR Level,
    _In_ ULONGLONG Keyword
    )
{
    //
    // Check if the event Level is lower than the level at which
    // the channel is enabled.
    // If the event Level is 0 or the channel is enabled at level 0,
    // all levels are enabled.
    //

    if ((Level <= EnableInfo->Level) || // This also covers the case of Level == 0.
        (EnableInfo->Level == 0)) {

        //
        // Check if Keyword is enabled
        //

        if ((Keyword == (ULONGLONG)0) ||
            ((Keyword & EnableInfo->MatchAnyKeyword) &&
             ((Keyword & EnableInfo->MatchAllKeyword) == EnableInfo->MatchAllKeyword))) {
            return TRUE;
        }
    }

    return FALSE;
}
#endif // MCGEN_LEVEL_KEYWORD_ENABLED_DEF

#if !defined(MCGEN_EVENT_ENABLED_DEF)
#define MCGEN_EVENT_ENABLED_DEF
//
// Determines whether the specified event would be considered as enabled based
// on the state of the specified context. Note that you may want to use
// MCGEN_ENABLE_CHECK instead of calling this function directly.
//
FORCEINLINE
BOOLEAN
McGenEventEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ PCEVENT_DESCRIPTOR EventDescriptor
    )
{
    return McGenLevelKeywordEnabled(EnableInfo, EventDescriptor->Level, EventDescriptor->Keyword);
}
#endif // MCGEN_EVENT_ENABLED_DEF

#if !defined(MCGEN_CONTROL_CALLBACK)
#define MCGEN_CONTROL_CALLBACK

DECLSPEC_NOINLINE __inline
VOID
__stdcall
McGenControlCallbackV2(
    _In_ LPCGUID SourceId,
    _In_ ULONG ControlCode,
    _In_ UCHAR Level,
    _In_ ULONGLONG MatchAnyKeyword,
    _In_ ULONGLONG MatchAllKeyword,
    _In_opt_ PEVENT_FILTER_DESCRIPTOR FilterData,
    _Inout_opt_ PVOID CallbackContext
    )
/*++

Routine Description:

    This is the notification callback for Windows Vista and later.

Arguments:

    SourceId - The GUID that identifies the session that enabled the provider.

    ControlCode - The parameter indicates whether the provider
                  is being enabled or disabled.

    Level - The level at which the event is enabled.

    MatchAnyKeyword - The bitmask of keywords that the provider uses to
                      determine the category of events that it writes.

    MatchAllKeyword - This bitmask additionally restricts the category
                      of events that the provider writes.

    FilterData - The provider-defined data.

    CallbackContext - The context of the callback that is defined when the provider
                      called EtwRegister to register itself.

Remarks:

    ETW calls this function to notify provider of enable/disable

--*/
{
    PMCGEN_TRACE_CONTEXT Ctx = (PMCGEN_TRACE_CONTEXT)CallbackContext;
    ULONG Ix;
#ifndef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    UNREFERENCED_PARAMETER(SourceId);
    UNREFERENCED_PARAMETER(FilterData);
#endif

    if (Ctx == NULL) {
        return;
    }

    switch (ControlCode) {

        case EVENT_CONTROL_CODE_ENABLE_PROVIDER:
            Ctx->Level = Level;
            Ctx->MatchAnyKeyword = MatchAnyKeyword;
            Ctx->MatchAllKeyword = MatchAllKeyword;
            Ctx->IsEnabled = EVENT_CONTROL_CODE_ENABLE_PROVIDER;

            for (Ix = 0; Ix < Ctx->EnableBitsCount; Ix += 1) {
                if (McGenLevelKeywordEnabled(Ctx, Ctx->EnableLevel[Ix], Ctx->EnableKeyWords[Ix]) != FALSE) {
                    Ctx->EnableBitMask[Ix >> 5] |= (1 << (Ix % 32));
                } else {
                    Ctx->EnableBitMask[Ix >> 5] &= ~(1 << (Ix % 32));
                }
            }
            break;

        case EVENT_CONTROL_CODE_DISABLE_PROVIDER:
            Ctx->IsEnabled = EVENT_CONTROL_CODE_DISABLE_PROVIDER;
            Ctx->Level = 0;
            Ctx->MatchAnyKeyword = 0;
            Ctx->MatchAllKeyword = 0;
            if (Ctx->EnableBitsCount > 0) {
                RtlZeroMemory(Ctx->EnableBitMask, (((Ctx->EnableBitsCount - 1) / 32) + 1) * sizeof(ULONG));
            }
            break;

        default:
            break;
    }

#ifdef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    //
    // Call user defined callback
    //
    MCGEN_PRIVATE_ENABLE_CALLBACK_V2(
        SourceId,
        ControlCode,
        Level,
        MatchAnyKeyword,
        MatchAllKeyword,
        FilterData,
        CallbackContext
        );
#endif // MCGEN_PRIVATE_ENABLE_CALLBACK_V2

    return;
}

#endif // MCGEN_CONTROL_CALLBACK

#ifndef McGenEventWrite_def
#define McGenEventWrite_def
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventWrite(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ LPCGUID ActivityId,
    _In_range_(1, 128) ULONG EventDataCount,
    _Inout_updates_(EventDataCount) EVENT_DATA_DESCRIPTOR* EventData
    )
{
    const USHORT UNALIGNED* Traits;

    // Some customized MCGEN_EVENTWRITETRANSFER macros might ignore ActivityId.
    UNREFERENCED_PARAMETER(ActivityId);

    Traits = (const USHORT UNALIGNED*)(UINT_PTR)Context->Logger;

    if (Traits == NULL) {
        EventData[0].Ptr = 0;
        EventData[0].Size = 0;
        EventData[0].Reserved = 0;
    } else {
        EventData[0].Ptr = (ULONG_PTR)Traits;
        EventData[0].Size = *Traits;
        EventData[0].Reserved = 2; // EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA
    }

    return MCGEN_EVENTWRITETRANSFER(
        Context->RegistrationHandle,
        Descriptor,
        ActivityId,
        NULL,
        EventDataCount,
        EventData);
}
#endif // McGenEventWrite_def

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister

#pragma warning(push)
#pragma warning(disable:6103)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ MCGEN_PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW.

Arguments:

    ProviderId - Provider ID to register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for the callback.

    RegHandle - Pointer to registration handle.

Remarks:

    Should not be called if the provider is already registered (i.e. should not
    be called if *RegHandle != 0). Repeatedly registering a provider is a bug
    and may indicate a race condition. However, for compatibility with previous
    behavior, this function will return SUCCESS in this case.

--*/
{
    ULONG Error;

    if (*RegHandle != 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTREGISTER(ProviderId, EnableCallback, CallbackContext, RegHandle);
    }

    return Error;
}
#pragma warning(pop)

DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW and set *RegHandle = 0.

Arguments:

    RegHandle - the pointer to the provider registration handle

Remarks:

    If provider has not been registered (i.e. if *RegHandle == 0),
    return SUCCESS. It is safe to call McGenEventUnregister even if the
    call to McGenEventRegister returned an error.

--*/
{
    ULONG Error;

    if(*RegHandle == 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTUNREGISTER(*RegHandle);
        *RegHandle = (REGHANDLE)0;
    }

    return Error;
}

#endif // McGenEventRegisterUnregister

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "FDI-Detours-Test" event count 7
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = ddc4f858-d5cb-481a-b0a4-80a30ba84033
EXTERN_C __declspec(selectany) const GUID FDI_DETOURS_TEST_PROVIDER = {0xddc4f858, 0xd5cb, 0x481a, {0xb0, 0xa4, 0x80, 0xa3, 0x0b, 0xa8, 0x40, 0x33}};

#ifndef FDI_DETOURS_TEST_PROVIDER_Traits
#define FDI_DETOURS_TEST_PROVIDER_Traits NULL
#endif // FDI_DETOURS_TEST_PROVIDER_Traits

//
// Channel
//
#define OPERATIONAL_CHANNEL 0x10
#define DEBUG_CHANNEL 0x11

//
// Levels
//
#define lvl_low_volume 0x10
#define lvl_medium_volume 0x11
#define lvl_high_volume 0x12

//
// Opcodes
//
#define opc_dll_load 0xa
#define opc_dll_unload 0xb
#define opc_routine_enter 0xc
#define opc_routine_exit 0xd
#define opc_completion_apc 0xe

//
// Tasks
//
#define tsk_module 0x1
EXTERN_C __declspec(selectany) const GUID ModuleId = {0x20c935e6, 0x532c, 0x4dce, {0xb1, 0x9f, 0x82, 0xdc, 0xeb, 0x22, 0xd9, 0xbf}};
#define tsk_intercept 0x2
EXTERN_C __declspec(selectany) const GUID InterceptId = {0xec8e8df3, 0xbdf3, 0x4a9b, {0x91, 0x95, 0x71, 0x60, 0xf0, 0x64, 0x1a, 0x73}};
#define tsk_provider 0x3
EXTERN_C __declspec(selectany) const GUID ETWProviderId = {0x333e0b20, 0x5200, 0x4068, {0xa6, 0x11, 0xce, 0xdd, 0x26, 0x11, 0x7a, 0xa5}};

//
// Keyword
//
#define kw_module 0x1
#define kw_pre_call 0x2
#define kw_post_call 0x4
#define kw_apc_call 0x8
#define kw_provider 0x10

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_dll_load = {0x1, 0x0, 0x10, 0x10, 0xa, 0x1, 0x8000000000000001};
#define evt_dll_load_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_dll_unload = {0x2, 0x0, 0x10, 0x10, 0xb, 0x1, 0x8000000000000001};
#define evt_dll_unload_value 0x2
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_api_call = {0x3, 0x0, 0x10, 0x12, 0xc, 0x2, 0x8000000000000002};
#define evt_api_call_value 0x3
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_api_return = {0x4, 0x0, 0x10, 0x12, 0xd, 0x2, 0x8000000000000004};
#define evt_api_return_value 0x4
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_apc = {0x5, 0x0, 0x10, 0x12, 0xe, 0x2, 0x8000000000000008};
#define evt_apc_value 0x5
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_dbg_provider_start = {0x6, 0x0, 0x11, 0x10, 0x1, 0x3, 0x4000000000000010};
#define evt_dbg_provider_start_value 0x6
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR evt_dbg_provider_exit = {0x7, 0x0, 0x11, 0x10, 0x2, 0x3, 0x4000000000000010};
#define evt_dbg_provider_exit_value 0x7

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG FDI_Detours_TestEnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG FDI_Detours_TestKeywords[5] = {0x8000000000000001, 0x8000000000000002, 0x8000000000000004, 0x8000000000000008, 0x4000000000000010};
EXTERN_C __declspec(selectany) const unsigned char FDI_Detours_TestLevels[5] = {16, 18, 18, 18, 16};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT FDI_DETOURS_TEST_PROVIDER_Context = {0, (ULONG_PTR)FDI_DETOURS_TEST_PROVIDER_Traits, 0, 0, 0, 0, 0, 0, 5, FDI_Detours_TestEnableBits, FDI_Detours_TestKeywords, FDI_Detours_TestLevels};

//
// Provider REGHANDLE
//
#define FDI_Detours_TestHandle (FDI_DETOURS_TEST_PROVIDER_Context.RegistrationHandle)

//
// This macro is set to 0, indicating that the EventWrite[Name] macros do not
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define FDI_DETOURS_TEST_PROVIDER_EventWriteActivity 0

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegisterFDI_Detours_Test
#define EventRegisterFDI_Detours_Test() McGenEventRegister(&FDI_DETOURS_TEST_PROVIDER, McGenControlCallbackV2, &FDI_DETOURS_TEST_PROVIDER_Context, &FDI_Detours_TestHandle)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuidFDI_Detours_Test
#define EventRegisterByGuidFDI_Detours_Test(Guid) McGenEventRegister(&(Guid), McGenControlCallbackV2, &FDI_DETOURS_TEST_PROVIDER_Context, &FDI_Detours_TestHandle)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregisterFDI_Detours_Test
#define EventUnregisterFDI_Detours_Test() McGenEventUnregister(&FDI_Detours_TestHandle)
#endif

//
// Enablement check macro for evt_dll_load
//
#define EventEnabledevt_dll_load() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 0)

//
// Event write macros for evt_dll_load
//
#define EventWriteevt_dll_load(Session_guid, File_spec, Host_name, Version_blob_size, Version_blob, File_hash_blob_size, File_hash_blob, Exports_blob_size, Exports_blob) \
        MCGEN_EVENT_ENABLED(evt_dll_load) \
        ? McTemplateU0jzshB1r3hB1r5hB1r3(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dll_load, Session_guid, File_spec, Host_name, Version_blob_size, Version_blob, File_hash_blob_size, File_hash_blob, Exports_blob_size, Exports_blob) : 0
#define EventWriteevt_dll_load_AssumeEnabled(Session_guid, File_spec, Host_name, Version_blob_size, Version_blob, File_hash_blob_size, File_hash_blob, Exports_blob_size, Exports_blob) \
        McTemplateU0jzshB1r3hB1r5hB1r3(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dll_load, Session_guid, File_spec, Host_name, Version_blob_size, Version_blob, File_hash_blob_size, File_hash_blob, Exports_blob_size, Exports_blob)

//
// Enablement check macro for evt_dll_unload
//
#define EventEnabledevt_dll_unload() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 0)

//
// Event write macros for evt_dll_unload
//
#define EventWriteevt_dll_unload(Session_guid, Statistics_blob_size, Statistics_blob_) \
        MCGEN_EVENT_ENABLED(evt_dll_unload) \
        ? McTemplateU0jhB1r1(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dll_unload, Session_guid, Statistics_blob_size, Statistics_blob_) : 0
#define EventWriteevt_dll_unload_AssumeEnabled(Session_guid, Statistics_blob_size, Statistics_blob_) \
        McTemplateU0jhB1r1(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dll_unload, Session_guid, Statistics_blob_size, Statistics_blob_)

//
// Enablement check macro for evt_api_call
//
#define EventEnabledevt_api_call() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 1)

//
// Event write macros for evt_api_call
//
#define EventWriteevt_api_call(Session_guid, Api_id, Arguments_blob_size, Arguments_blob) \
        MCGEN_EVENT_ENABLED(evt_api_call) \
        ? McTemplateU0jqhB1r2(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_api_call, Session_guid, Api_id, Arguments_blob_size, Arguments_blob) : 0
#define EventWriteevt_api_call_AssumeEnabled(Session_guid, Api_id, Arguments_blob_size, Arguments_blob) \
        McTemplateU0jqhB1r2(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_api_call, Session_guid, Api_id, Arguments_blob_size, Arguments_blob)

//
// Enablement check macro for evt_api_return
//
#define EventEnabledevt_api_return() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 2)

//
// Event write macros for evt_api_return
//
#define EventWriteevt_api_return(Session_guid, Api_id, Return_value, Output_blob_size, Output_blob) \
        MCGEN_EVENT_ENABLED(evt_api_return) \
        ? McTemplateU0jqxhB1r3(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_api_return, Session_guid, Api_id, Return_value, Output_blob_size, Output_blob) : 0
#define EventWriteevt_api_return_AssumeEnabled(Session_guid, Api_id, Return_value, Output_blob_size, Output_blob) \
        McTemplateU0jqxhB1r3(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_api_return, Session_guid, Api_id, Return_value, Output_blob_size, Output_blob)

//
// Enablement check macro for evt_apc
//
#define EventEnabledevt_apc() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 3)

//
// Event write macros for evt_apc
//
#define EventWriteevt_apc(Session_guid, Api_id, Parameter_blob_size, Parameter_blob) \
        MCGEN_EVENT_ENABLED(evt_apc) \
        ? McTemplateU0jqhB1r2(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_apc, Session_guid, Api_id, Parameter_blob_size, Parameter_blob) : 0
#define EventWriteevt_apc_AssumeEnabled(Session_guid, Api_id, Parameter_blob_size, Parameter_blob) \
        McTemplateU0jqhB1r2(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_apc, Session_guid, Api_id, Parameter_blob_size, Parameter_blob)

//
// Enablement check macro for evt_dbg_provider_start
//
#define EventEnabledevt_dbg_provider_start() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 4)

//
// Event write macros for evt_dbg_provider_start
//
#define EventWriteevt_dbg_provider_start(Name, Version, Build_date, Build_time) \
        MCGEN_EVENT_ENABLED(evt_dbg_provider_start) \
        ? McTemplateU0ssss(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dbg_provider_start, Name, Version, Build_date, Build_time) : 0
#define EventWriteevt_dbg_provider_start_AssumeEnabled(Name, Version, Build_date, Build_time) \
        McTemplateU0ssss(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dbg_provider_start, Name, Version, Build_date, Build_time)

//
// Enablement check macro for evt_dbg_provider_exit
//
#define EventEnabledevt_dbg_provider_exit() MCGEN_EVENT_BIT_SET(FDI_Detours_TestEnableBits, 4)

//
// Event write macros for evt_dbg_provider_exit
//
#define EventWriteevt_dbg_provider_exit(Status) \
        MCGEN_EVENT_ENABLED(evt_dbg_provider_exit) \
        ? McTemplateU0q(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dbg_provider_exit, Status) : 0
#define EventWriteevt_dbg_provider_exit_AssumeEnabled(Status) \
        McTemplateU0q(&FDI_DETOURS_TEST_PROVIDER_Context, &evt_dbg_provider_exit, Status)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Template Functions
//
//
//Template from manifest : Unload
//
#ifndef McTemplateU0jhB1r1_def
#define McTemplateU0jhB1r1_def
ETW_INLINE
ULONG
McTemplateU0jhB1r1(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_ const GUID*  _Arg0,
    _In_ const unsigned short  _Arg1,
    _In_reads_(1*_Arg1) const unsigned char*  _Arg2
    )
{
#define McTemplateU0jhB1r1_ARGCOUNT 3

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0jhB1r1_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],_Arg0, sizeof(GUID)  );

    EventDataDescCreate(&EventData[2],&_Arg1, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[3],_Arg2, (ULONG)sizeof(char)*1*_Arg1);  // Blob containing _Arg1 concatenated strings; each string has the same length (1)

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0jhB1r1_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0jhB1r1_def

//
//Template from manifest : Call
//
#ifndef McTemplateU0jqhB1r2_def
#define McTemplateU0jqhB1r2_def
ETW_INLINE
ULONG
McTemplateU0jqhB1r2(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_ const GUID*  _Arg0,
    _In_ const unsigned int  _Arg1,
    _In_ const unsigned short  _Arg2,
    _In_reads_(1*_Arg2) const unsigned char*  _Arg3
    )
{
#define McTemplateU0jqhB1r2_ARGCOUNT 4

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0jqhB1r2_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],_Arg0, sizeof(GUID)  );

    EventDataDescCreate(&EventData[2],&_Arg1, sizeof(const unsigned int)  );

    EventDataDescCreate(&EventData[3],&_Arg2, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[4],_Arg3, (ULONG)sizeof(char)*1*_Arg2);  // Blob containing _Arg2 concatenated strings; each string has the same length (1)

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0jqhB1r2_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0jqhB1r2_def

//
//Template from manifest : Return
//
#ifndef McTemplateU0jqxhB1r3_def
#define McTemplateU0jqxhB1r3_def
ETW_INLINE
ULONG
McTemplateU0jqxhB1r3(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_ const GUID*  _Arg0,
    _In_ const unsigned int  _Arg1,
    _In_ const unsigned __int64  _Arg2,
    _In_ const unsigned short  _Arg3,
    _In_reads_(1*_Arg3) const unsigned char*  _Arg4
    )
{
#define McTemplateU0jqxhB1r3_ARGCOUNT 5

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0jqxhB1r3_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],_Arg0, sizeof(GUID)  );

    EventDataDescCreate(&EventData[2],&_Arg1, sizeof(const unsigned int)  );

    EventDataDescCreate(&EventData[3],&_Arg2, sizeof(const unsigned __int64)  );

    EventDataDescCreate(&EventData[4],&_Arg3, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[5],_Arg4, (ULONG)sizeof(char)*1*_Arg3);  // Blob containing _Arg3 concatenated strings; each string has the same length (1)

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0jqxhB1r3_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0jqxhB1r3_def

//
//Template from manifest : Load
//
#ifndef McTemplateU0jzshB1r3hB1r5hB1r3_def
#define McTemplateU0jzshB1r3hB1r5hB1r3_def
ETW_INLINE
ULONG
McTemplateU0jzshB1r3hB1r5hB1r3(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_ const GUID*  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCSTR  _Arg2,
    _In_ const unsigned short  _Arg3,
    _In_reads_(1*_Arg3) const unsigned char*  _Arg4,
    _In_ const unsigned short  _Arg5,
    _In_reads_(1*_Arg5) const unsigned char*  _Arg6,
    _In_ const unsigned short  _Arg7,
    _In_reads_(1*_Arg3) const unsigned char*  _Arg8
    )
{
#define McTemplateU0jzshB1r3hB1r5hB1r3_ARGCOUNT 9

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0jzshB1r3hB1r5hB1r3_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],_Arg0, sizeof(GUID)  );

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : "NULL",
                        (_Arg2 != NULL) ? (ULONG)((strlen(_Arg2) + 1) * sizeof(char)) : (ULONG)sizeof("NULL"));

    EventDataDescCreate(&EventData[4],&_Arg3, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[5],_Arg4, (ULONG)sizeof(char)*1*_Arg3);  // Blob containing _Arg3 concatenated strings; each string has the same length (1)

    EventDataDescCreate(&EventData[6],&_Arg5, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[7],_Arg6, (ULONG)sizeof(char)*1*_Arg5);  // Blob containing _Arg5 concatenated strings; each string has the same length (1)

    EventDataDescCreate(&EventData[8],&_Arg7, sizeof(const unsigned short)  );

    EventDataDescCreate(&EventData[9],_Arg8, (ULONG)sizeof(char)*1*_Arg3);  // Blob containing _Arg3 concatenated strings; each string has the same length (1)

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0jzshB1r3hB1r5hB1r3_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0jzshB1r3hB1r5hB1r3_def

//
//Template from manifest : Message_status
//
#ifndef McTemplateU0q_def
#define McTemplateU0q_def
ETW_INLINE
ULONG
McTemplateU0q(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_ const unsigned int  _Arg0
    )
{
#define McTemplateU0q_ARGCOUNT 1

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0q_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],&_Arg0, sizeof(const unsigned int)  );

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0q_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0q_def

//
//Template from manifest : AStrings4
//
#ifndef McTemplateU0ssss_def
#define McTemplateU0ssss_def
ETW_INLINE
ULONG
McTemplateU0ssss(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCSTR  _Arg0,
    _In_opt_ PCSTR  _Arg1,
    _In_opt_ PCSTR  _Arg2,
    _In_opt_ PCSTR  _Arg3
    )
{
#define McTemplateU0ssss_ARGCOUNT 4

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0ssss_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : "NULL",
                        (_Arg0 != NULL) ? (ULONG)((strlen(_Arg0) + 1) * sizeof(char)) : (ULONG)sizeof("NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : "NULL",
                        (_Arg1 != NULL) ? (ULONG)((strlen(_Arg1) + 1) * sizeof(char)) : (ULONG)sizeof("NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : "NULL",
                        (_Arg2 != NULL) ? (ULONG)((strlen(_Arg2) + 1) * sizeof(char)) : (ULONG)sizeof("NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : "NULL",
                        (_Arg3 != NULL) ? (ULONG)((strlen(_Arg3) + 1) * sizeof(char)) : (ULONG)sizeof("NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0ssss_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0ssss_def

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

#if defined(__cplusplus)
};
#endif

#define MSG_FDI_Detours_Test_Keyword__module_message 0x10000001L
#define MSG_FDI_Detours_Test_Keyword__pre_call_message 0x10000002L
#define MSG_FDI_Detours_Test_Keyword__post_call_message 0x10000003L
#define MSG_FDI_Detours_Test_Keyword__apc_call_message 0x10000004L
#define MSG_FDI_Detours_Test_Keyword_Provider_message 0x10000005L
#define MSG_opcode_Start                     0x30000001L
#define MSG_opcode_Stop                      0x30000002L
#define MSG_FDI_Detours_Test_opcode__dll_load_message 0x3000000AL
#define MSG_FDI_Detours_Test_opcode__dll_unload_message 0x3000000BL
#define MSG_FDI_Detours_Test_opcode__routine_enter_message 0x3000000CL
#define MSG_FDI_Detours_Test_opcode__routine_exit_message 0x3000000DL
#define MSG_FDI_Detours_Test_opcode__completion_apc_message 0x3000000EL
#define MSG_FDI_Detours_Test_level__low_volume_message 0x50000010L
#define MSG_FDI_Detours_Test_level__medium_volume_message 0x50000011L
#define MSG_FDI_Detours_Test_level__high_volume_message 0x50000012L
#define MSG_FDI_Detours_Test_task__module_message 0x70000001L
#define MSG_FDI_Detours_Test_task__intercept_message 0x70000002L
#define MSG_FDI_Detours_Test_task__provider_message 0x70000003L
#define MSG_FDI_Detours_Test_channel_OPERATIONAL_CHANNEL_message 0x90000001L
#define MSG_FDI_Detours_Test_channel_DEBUG_CHANNEL_message 0x90000002L
#define MSG_FDI_Detours_Test_event_1_message 0xB0000001L
#define MSG_FDI_Detours_Test_event_2_message 0xB0000002L
#define MSG_FDI_Detours_Test_event_3_message 0xB0000003L
#define MSG_FDI_Detours_Test_event_4_message 0xB0000004L
#define MSG_FDI_Detours_Test_event_5_message 0xB0000005L
#define MSG_FDI_Detours_Test_event_6_message 0xB0000006L
#define MSG_FDI_Detours_Test_event_7_message 0xB0000007L
